 CREATE TABLE restaurants(
 
	r_id INTEGER,
    r_name VARCHAR(50),
    cuisine VARCHAR(50)

);

INSERT INTO restaurants (r_id, r_name, cuisine)
VALUES
    (1, 'Dominos', 'Italian'),
    (2, 'KFC', 'American'),
    (3, 'Pizza Hut', 'Italian'),
    (4, 'Dosa Plaza', 'South Indian'),
    (5, 'McDonald\'s', 'American'),
    (6, 'Burger King', 'American'),
    (7, 'Mainland China', 'Chinese'),
    (8, 'Barbeque Nation', 'North Indian'),
    (9, 'Saravana Bhavan', 'South Indian'),
    (10, 'Moti Mahal', 'North Indian'),
    (11, 'Annapurna Bhavan', 'South Indian'),
    (12, 'Karim\'s', 'North Indian'),
    (13, 'Cafe Coffee Day', 'Beverages'),
    (14, 'Haldiram\'s', 'North Indian'),
    (15, 'Goli Vada Pav', 'Street Food'),
    (16, 'Subway', 'American'),
    (17, 'Rajdhani Thali', 'Gujarati'),
    (18, 'Banana Leaf', 'South Indian'),
    (19, 'Indian Coffee House', 'Beverages'),
    (20, 'Bikanervala', 'North Indian'),
    (21, 'Naturals Ice Cream', 'Desserts'),
    (22, 'MTR', 'South Indian'),
    (23, 'Mughal Darbar', 'North Indian'),
    (24, 'Malgudi Days', 'South Indian'),
    (25, 'Sagar Ratna', 'South Indian'),
    (26, 'Paradise Biryani', 'Hyderabadi'),
    (27, 'The Yellow Chilli', 'North Indian'),
    (28, 'Balaji Santosh', 'South Indian'),
    (29, 'Cafe Madras', 'South Indian'),
    (30, 'Indigo Deli', 'European'),
    (31, 'Little Italy', 'Italian'),
    (32, 'Pind Balluchi', 'Punjabi'),
    (33, 'Urban Tadka', 'North Indian'),
    (34, 'Wah Ji Wah', 'Punjabi'),
    (35, 'Lazeez Affaire', 'North Indian'),
    (36, 'Punjabi By Nature', 'Punjabi'),
    (37, 'Sigree', 'North Indian'),
    (38, 'Shree Mithai', 'South Indian'),
    (39, 'Khan Chacha', 'Mughlai'),
    (40, 'Bade Miya', 'Mughlai'),
    (41, 'Theobroma', 'Bakery'),
    (42, 'Monginis', 'Bakery'),
    (43, 'Keventers', 'Beverages'),
    (44, 'Mad Over Donuts', 'Desserts'),
    (45, 'Chitale Bandhu', 'Sweets'),
    (46, 'Cafe Mondegar', 'Continental'),
    (47, 'Tunday Kababi', 'Mughlai'),
    (48, 'Rayalaseema Ruchulu', 'South Indian'),
    (49, 'Saffron', 'North Indian'),
    (50, 'SpiceKlub', 'North Indian'),
    (51, 'Chutneys', 'South Indian'),
    (52, 'Al-Bake', 'Mughlai'),
    (53, 'Koshy\'s', 'Continental'),
    (54, 'China Gate', 'Chinese'),
    (55, 'Nando\'s', 'Peri-Peri'),
    (56, 'The Fatty Bao', 'Asian'),
    (57, 'Gajalee', 'Seafood'),
    (58, 'Mahesh Lunch Home', 'Seafood'),
    (59, 'Amritsari Kulcha', 'Punjabi'),
    (60, 'Basilico', 'Italian'),
    (61, 'Chokhi Dhani', 'Rajasthani'),
    (62, 'Kake Da Hotel', 'Punjabi'),
    (63, 'The Spice Route', 'Asian'),
    (64, 'Karavalli', 'South Indian'),
    (65, 'Dakshin', 'South Indian'),
    (66, 'Khanasutra', 'North Indian'),
    (67, 'Masala Library', 'North Indian'),
    (68, 'Olive Bar & Kitchen', 'Mediterranean'),
    (69, 'Bombay Brasserie', 'North Indian'),
    (70, 'Biryani Blues', 'Hyderabadi'),
    (71, 'Copper Chimney', 'North Indian'),
    (72, 'Pa Pa Ya', 'Asian'),
    (73, 'The Bombay Canteen', 'Modern Indian'),
    (74, 'Chili\'s', 'American'),
    (75, 'SodaBottleOpenerWala', 'Parsi'),
    (76, 'Smally\'s', 'American'),
    (77, 'Mamagoto', 'Asian'),
    (78, 'Hokey Pokey', 'Desserts'),
    (79, 'Sunny\'s', 'Italian'),
    (80, 'Truffles', 'American'),
    (81, 'Samarkand', 'North Indian'),
    (82, 'Shiv Sagar', 'South Indian'),
    (83, 'Meghana Foods', 'South Indian'),
    (84, 'Vidyaranya Bhavan', 'South Indian'),
    (85, 'Bombay Burger', 'Street Food'),
    (86, 'Vidyarthi Bhavan', 'South Indian'),
    (87, 'Thalassery Restaurant', 'Kerala'),
    (88, 'Bhagat Tarachand', 'North Indian'),
    (89, 'Aaswad', 'Maharashtrian'),
    (90, 'Spices & Flavors', 'North Indian'),
    (91, 'Faasos', 'Wraps'),
    (92, 'Domino\'s', 'Pizza'),
    (93, 'Royal Afghan', 'North Indian'),
    (94, 'Isha\'s', 'Continental'),
    (95, 'Teekha', 'Street Food'),
    (96, 'Mylari', 'South Indian'),
    (97, 'Shree Krishna Sweets', 'Sweets'),
    (98, 'Shree Nandhini', 'South Indian'),
    (99, 'Hotel Saravana Bhavan', 'South Indian'),
    (100, 'Shivaji Military Hotel', 'South Indian');