CREATE TABLE food
(
	f_id INTEGER,
    f_name VARCHAR(50),
    `type` VARCHAR(50)
);

INSERT INTO food (f_id, f_name, type)
VALUES
    (1, 'Non-Veg Pizza', 'Non Vegetarian'),
    (2, 'Veg Pizza', 'Vegetarian'),
    (3, 'Choco Lava Cake', 'Vegetarian'),
    (4, 'Chicken Wings', 'Non Vegetarian'),
    (5, 'Chicken Popcorn', 'Non Vegetarian'),
    (6, 'Rice Meal', 'Vegetarian'),
    (7, 'Roti Meal', 'Vegetarian'),
    (8, 'Masala Dosa', 'Vegetarian'),
    (9, 'Rava Idli', 'Vegetarian'),
    (10, 'Schezwan Noodles', 'Vegetarian'),
    (11, 'Veg Manchurian', 'Vegetarian'),
    (12, 'Paneer Tikka', 'Vegetarian'),
    (13, 'Chicken Biryani', 'Non Vegetarian'),
    (14, 'Veg Biryani', 'Vegetarian'),
    (15, 'Pasta Alfredo', 'Vegetarian'),
    (16, 'Grilled Chicken', 'Non Vegetarian'),
    (17, 'Fish Curry', 'Non Vegetarian'),
    (18, 'Butter Chicken', 'Non Vegetarian'),
    (19, 'Dal Makhani', 'Vegetarian'),
    (20, 'Palak Paneer', 'Vegetarian'),
    (21, 'Chole Bhature', 'Vegetarian'),
    (22, 'Rajma Chawal', 'Vegetarian'),
    (23, 'Aloo Paratha', 'Vegetarian'),
    (24, 'Mutton Rogan Josh', 'Non Vegetarian'),
    (25, 'Egg Curry', 'Non Vegetarian'),
    (26, 'Paneer Butter Masala', 'Vegetarian'),
    (27, 'Chicken Tandoori', 'Non Vegetarian'),
    (28, 'Vegetable Pulao', 'Vegetarian'),
    (29, 'Gobi Manchurian', 'Vegetarian'),
    (30, 'Pav Bhaji', 'Vegetarian'),
    (31, 'Samosa', 'Vegetarian'),
    (32, 'Mutton Kebab', 'Non Vegetarian'),
    (33, 'Hakka Noodles', 'Vegetarian'),
    (34, 'Paneer Pakora', 'Vegetarian'),
    (35, 'Chicken Shawarma', 'Non Vegetarian'),
    (36, 'Idli Sambar', 'Vegetarian'),
    (37, 'Kadhi Chawal', 'Vegetarian'),
    (38, 'Bacon Sandwich', 'Non Vegetarian'),
    (39, 'Chicken Caesar Salad', 'Non Vegetarian'),
    (40, 'Mutton Biryani', 'Non Vegetarian'),
    (41, 'Vegetable Fried Rice', 'Vegetarian'),
    (42, 'Mushroom Masala', 'Vegetarian'),
    (43, 'Paneer Bhurji', 'Vegetarian'),
    (44, 'Chicken Malai Tikka', 'Non Vegetarian'),
    (45, 'Fish Fry', 'Non Vegetarian'),
    (46, 'Egg Fried Rice', 'Non Vegetarian'),
    (47, 'Cheese Burger', 'Vegetarian'),
    (48, 'Chicken Burger', 'Non Vegetarian'),
    (49, 'Mutton Curry', 'Non Vegetarian'),
    (50, 'Veg Hakka Noodles', 'Vegetarian'),
    (51, 'Garlic Bread', 'Vegetarian'),
    (52, 'Veg Spring Roll', 'Vegetarian'),
    (53, 'Chicken Momos', 'Non Vegetarian'),
    (54, 'Veg Momos', 'Vegetarian'),
    (55, 'Paneer Parantha', 'Vegetarian'),
    (56, 'Shahi Paneer', 'Vegetarian'),
    (57, 'Keema Paratha', 'Non Vegetarian'),
    (58, 'Dal Tadka', 'Vegetarian'),
    (59, 'Egg Bhurji', 'Non Vegetarian'),
    (60, 'Mutton Seekh Kebab', 'Non Vegetarian'),
    (61, 'Chicken Fried Rice', 'Non Vegetarian'),
    (62, 'Vegetable Sandwich', 'Vegetarian'),
    (63, 'Pasta Arrabbiata', 'Vegetarian'),
    (64, 'Chicken Korma', 'Non Vegetarian'),
    (65, 'Malai Kofta', 'Vegetarian'),
    (66, 'Mutton Keema', 'Non Vegetarian'),
    (67, 'Egg Roll', 'Non Vegetarian'),
    (68, 'Veg Roll', 'Vegetarian'),
    (69, 'Paneer Roll', 'Vegetarian'),
    (70, 'Fish Tikka', 'Non Vegetarian'),
    (71, 'Veg Handi', 'Vegetarian'),
    (72, 'Chicken Handi', 'Non Vegetarian'),
    (73, 'Bhel Puri', 'Vegetarian'),
    (74, 'Pani Puri', 'Vegetarian'),
    (75, 'Chicken 65', 'Non Vegetarian'),
    (76, 'Paneer 65', 'Vegetarian'),
    (77, 'Gulab Jamun', 'Vegetarian'),
    (78, 'Rasgulla', 'Vegetarian'),
    (79, 'Kadai Chicken', 'Non Vegetarian'),
    (80, 'Chicken Chettinad', 'Non Vegetarian'),
    (81, 'Prawn Masala', 'Non Vegetarian'),
    (82, 'Vegetable Korma', 'Vegetarian'),
    (83, 'Beef Curry', 'Non Vegetarian'),
    (84, 'Prawn Biryani', 'Non Vegetarian'),
    (85, 'Chicken Lollipop', 'Non Vegetarian'),
    (86, 'Paneer Lababdar', 'Vegetarian'),
    (87, 'Vegetable Jalfrezi', 'Vegetarian'),
    (88, 'Mutton Do Pyaza', 'Non Vegetarian'),
    (89, 'Paneer Shashlik', 'Vegetarian'),
    (90, 'Paneer Tikka Masala', 'Vegetarian'),
    (91, 'Chicken Stew', 'Non Vegetarian'),
    (92, 'Prawn Fry', 'Non Vegetarian'),
    (93, 'Vegetable Pakora', 'Vegetarian'),
    (94, 'Fish Curry Rice', 'Non Vegetarian'),
    (95, 'Chilli Chicken', 'Non Vegetarian'),
    (96, 'Paneer Chilli', 'Vegetarian'),
    (97, 'Chicken Schezwan', 'Non Vegetarian'),
    (98, 'Paneer Schezwan', 'Vegetarian'),
    (99, 'Mutton Boti', 'Non Vegetarian'),
    (100, 'Sambar Rice', 'Vegetarian');