CREATE DATABASE ZOMATO_DATA;
USE zomato_data;

CREATE TABLE USERS(

	user_id INTEGER,
    name VARCHAR(50),
    email VARCHAR(50),
    password VARCHAR(40)
);

INSERT INTO users (user_id, name, email, password)
VALUES
    (1, 'Amit Sharma', 'amit.sharma@example.com', 'password1'),
    (2, 'Priya Mehta', 'priya.mehta@example.com', 'password2'),
    (3, 'Ravi Kumar', 'ravi.kumar@example.com', 'password3'),
    (4, 'Sunita Singh', 'sunita.singh@example.com', 'password4'),
    (5, 'Vikram Patel', 'vikram.patel@example.com', 'password5'),
    (6, 'Anjali Rao', 'anjali.rao@example.com', 'password6'),
    (7, 'Rajesh Verma', 'rajesh.verma@example.com', 'password7'),
    (8, 'Neha Gupta', 'neha.gupta@example.com', 'password8'),
    (9, 'Suresh Reddy', 'suresh.reddy@example.com', 'password9'),
    (10, 'Meena Desai', 'meena.desai@example.com', 'password10'),
    (11, 'Kiran Joshi', 'kiran.joshi@example.com', 'password11'),
    (12, 'Ritu Chauhan', 'ritu.chauhan@example.com', 'password12'),
    (13, 'Aakash Khanna', 'aakash.khanna@example.com', 'password13'),
    (14, 'Sneha Iyer', 'sneha.iyer@example.com', 'password14'),
    (15, 'Nikhil Bhatia', 'nikhil.bhatia@example.com', 'password15'),
    (16, 'Pooja Nair', 'pooja.nair@example.com', 'password16'),
    (17, 'Rohan Malhotra', 'rohan.malhotra@example.com', 'password17'),
    (18, 'Shweta Ghosh', 'shweta.ghosh@example.com', 'password18'),
    (19, 'Arjun Yadav', 'arjun.yadav@example.com', 'password19'),
    (20, 'Divya Pandey', 'divya.pandey@example.com', 'password20'),
    (21, 'Vivek Deshmukh', 'vivek.deshmukh@example.com', 'password21'),
    (22, 'Preeti Kaur', 'preeti.kaur@example.com', 'password22'),
    (23, 'Manoj Shetty', 'manoj.shetty@example.com', 'password23'),
    (24, 'Anita Kulkarni', 'anita.kulkarni@example.com', 'password24'),
    (25, 'Rakesh Agrawal', 'rakesh.agrawal@example.com', 'password25'),
    (26, 'Rashmi Sharma', 'rashmi.sharma@example.com', 'password26'),
    (27, 'Vikas Srivastava', 'vikas.srivastava@example.com', 'password27'),
    (28, 'Sakshi Jain', 'sakshi.jain@example.com', 'password28'),
    (29, 'Gaurav Thakur', 'gaurav.thakur@example.com', 'password29'),
    (30, 'Kavita Kapoor', 'kavita.kapoor@example.com', 'password30'),
    (31, 'Sandeep Bajaj', 'sandeep.bajaj@example.com', 'password31'),
    (32, 'Bhavana Reddy', 'bhavana.reddy@example.com', 'password32'),
    (33, 'Rahul Ahuja', 'rahul.ahuja@example.com', 'password33'),
    (34, 'Vidya Menon', 'vidya.menon@example.com', 'password34'),
    (35, 'Aman Sinha', 'aman.sinha@example.com', 'password35'),
    (36, 'Shalini Roy', 'shalini.roy@example.com', 'password36'),
    (37, 'Ashok Pillai', 'ashok.pillai@example.com', 'password37'),
    (38, 'Nisha Tiwari', 'nisha.tiwari@example.com', 'password38'),
    (39, 'Karthik Rao', 'karthik.rao@example.com', 'password39'),
    (40, 'Megha Chatterjee', 'megha.chatterjee@example.com', 'password40'),
    (41, 'Pradeep Saxena', 'pradeep.saxena@example.com', 'password41'),
    (42, 'Anu Pillai', 'anu.pillai@example.com', 'password42'),
    (43, 'Ajay Mishra', 'ajay.mishra@example.com', 'password43'),
    (44, 'Laxmi Patil', 'laxmi.patil@example.com', 'password44'),
    (45, 'Shivani Sengupta', 'shivani.sengupta@example.com', 'password45'),
    (46, 'Mahesh Chawla', 'mahesh.chawla@example.com', 'password46'),
    (47, 'Sudha Kapoor', 'sudha.kapoor@example.com', 'password47'),
    (48, 'Arvind Reddy', 'arvind.reddy@example.com', 'password48'),
    (49, 'Geeta Agarwal', 'geeta.agarwal@example.com', 'password49'),
    (50, 'Vinod Menon', 'vinod.menon@example.com', 'password50'),
    (51, 'Rajni Nair', 'rajni.nair@example.com', 'password51'),
    (52, 'Anoop Bhardwaj', 'anoop.bhardwaj@example.com', 'password52'),
    (53, 'Sandhya Chauhan', 'sandhya.chauhan@example.com', 'password53'),
    (54, 'Devendra Singh', 'devendra.singh@example.com', 'password54'),
    (55, 'Ananya Mukherjee', 'ananya.mukherjee@example.com', 'password55'),
    (56, 'Pavan Naidu', 'pavan.naidu@example.com', 'password56'),
    (57, 'Sonal Jain', 'sonal.jain@example.com', 'password57'),
    (58, 'Suraj Gupta', 'suraj.gupta@example.com', 'password58'),
    (59, 'Smita Iyer', 'smita.iyer@example.com', 'password59'),
    (60, 'Lokesh Bhat', 'lokesh.bhat@example.com', 'password60'),
    (61, 'Sonia Arora', 'sonia.arora@example.com', 'password61'),
    (62, 'Dev Patel', 'dev.patel@example.com', 'password62'),
    (63, 'Usha Rani', 'usha.rani@example.com', 'password63'),
    (64, 'Manish Reddy', 'manish.reddy@example.com', 'password64'),
    (65, 'Swati Nair', 'swati.nair@example.com', 'password65'),
    (66, 'Yogesh Desai', 'yogesh.desai@example.com', 'password66'),
    (67, 'Jaya Verma', 'jaya.verma@example.com', 'password67'),
    (68, 'Harish Kumar', 'harish.kumar@example.com', 'password68'),
    (69, 'Ruchi Bhatnagar', 'ruchi.bhatnagar@example.com', 'password69'),
    (70, 'Tarun Ghosh', 'tarun.ghosh@example.com', 'password70'),
    (71, 'Alok Reddy', 'alok.reddy@example.com', 'password71'),
    (72, 'Kanchan Sharma', 'kanchan.sharma@example.com', 'password72'),
    (73, 'Sanjeev Menon', 'sanjeev.menon@example.com', 'password73'),
    (74, 'Chitra Singh', 'chitra.singh@example.com', 'password74'),
    (75, 'Ranjan Deshmukh', 'ranjan.deshmukh@example.com', 'password75'),
    (76, 'Aarti Rao', 'aarti.rao@example.com', 'password76'),
    (77, 'Vishal Jain', 'vishal.jain@example.com', 'password77'),
    (78, 'Seema Sharma', 'seema.sharma@example.com', 'password78'),
    (79, 'Akshay Verma', 'akshay.verma@example.com', 'password79'),
    (80, 'Rakhi Kulkarni', 'rakhi.kulkarni@example.com', 'password80'),
    (81, 'Madhav Gupta', 'madhav.gupta@example.com', 'password81'),
    (82, 'Parvati Reddy', 'parvati.reddy@example.com', 'password82'),
    (83, 'Dhruv Kumar', 'dhruv.kumar@example.com', 'password83'),
    (84, 'Nandini Nair', 'nandini.nair@example.com', 'password84'),
    (85, 'Keshav Iyer', 'keshav.iyer@example.com', 'password85'),
    (86, 'Sarita Bhatia', 'sarita.bhatia@example.com', 'password86'),
    (87, 'Siddharth Sharma', 'siddharth.sharma@example.com', 'password87'),
    (88, 'Veena Kapoor', 'veena.kapoor@example.com', 'password88'),
    (89, 'Mohan Shetty', 'mohan.shetty@example.com', 'password89'),
    (90, 'Anand Pillai', 'anand.pillai@example.com', 'password90'),
    (91, 'Sumita Desai', 'sumita.desai@example.com', 'password91'),
    (92, 'Naresh Patel', 'naresh.patel@example.com', 'password92'),
    (93, 'Megha Yadav', 'megha.yadav@example.com', 'password93'),
    (94, 'Deepak Reddy', 'deepak.reddy@example.com', 'password94'),
    (95, 'Pallavi Rao', 'pallavi.rao@example.com', 'password95'),
    (96, 'Girish Verma', 'girish.verma@example.com', 'password96'),
    (97, 'Ishita Kapoor', 'ishita.kapoor@example.com', 'password97'),
    (98, 'Ravindra Joshi', 'ravindra.joshi@example.com', 'password98'),
    (99, 'Mamta Sharma', 'mamta.sharma@example.com', 'password99'),
    (100, 'Aditya Khurana', 'aditya.khurana@example.com', 'password100');
    
    SELECT * FROM users;
    
    
